# Generated by Django 5.1.15 on 2026-04-27 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('analysis', models.TextField()),
                ('analysis_model', models.CharField(max_length=30)),
                ('generated_at', models.DateTimeField()),
                ('snapshot_json', models.JSONField(default=dict, help_text='Serialized indicator snapshot sent to the model.')),
                ('recession_probability', models.FloatField(blank=True, help_text='0–100 score.', null=True)),
                ('composite_health_score', models.FloatField(blank=True, help_text='0–100 score.', null=True)),
            ],
            options={
                'verbose_name_plural': 'Daily Analyses',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EconomicSeries',
            fields=[
                ('series_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('macro', 'Macro'), ('labor', 'Labor'), ('housing', 'Housing'), ('markets', 'Markets'), ('consumer', 'Consumer & Business')], max_length=20)),
                ('source', models.CharField(choices=[('fred', 'FRED'), ('yfinance', 'yfinance')], default='fred', max_length=20)),
                ('units', models.CharField(blank=True, max_length=100)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='monthly', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('invert_for_score', models.BooleanField(default=False, help_text='True for series where high values are bad (unemployment, claims, VIX).')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Economic Series',
                'ordering': ['category', 'series_id'],
            },
        ),
        migrations.CreateModel(
            name='FetchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='failed', max_length=10)),
                ('series_fetched', models.IntegerField(default=0)),
                ('series_failed', models.IntegerField(default=0)),
                ('points_written', models.IntegerField(default=0)),
                ('error_detail', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.FloatField()),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='economy.economicseries')),
            ],
            options={
                'ordering': ['series', 'date'],
                'indexes': [models.Index(fields=['series', 'date'], name='economy_dat_series__8522d7_idx')],
                'unique_together': {('series', 'date')},
            },
        ),
    ]
